project:
  type: website
  output-dir: docs

website:
  title: "My Business Analytics Journey"
  navbar:
    left:
      - text: "Blog"
        href: blog.qmd
    right:
      - text: "About Me"
        href: index.qmd
      - icon: github
        href: https://github.com/nnam0004
      - icon: linkedin
        href: https://www.linkedin.com/in/naharnamdhari
      - icon: envelope
        href: mailto:nnam0004@student.monash.edu

format:
  html:
    theme: sandstone
    css: styles.css

